"""
Baseline schema: every table and index dltrack has today, in one revision.

Revision ID: 0001
Revises:
Create Date: 2026-10-03

Hand-written rather than autogenerated: delegating to `MetaData.create_all`/`drop_all` reuses the
exact table/index construction every store has always used (custom types, `Identity()` primary
keys, dialect-specific defaults and all) instead of relying on autogenerate's rendering of that
construction into literal `op.create_table(...)` calls for a from-scratch schema. A future revision
that changes one or two tables is the case autogenerate is actually good at, and where it's used.
"""

from __future__ import annotations

from alembic import op

from dltrack.serve._backend._sql_store_base import build_metadata

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create every table and index."""
    metadata, _ = build_metadata()
    metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    """Drop every table and index."""
    metadata, _ = build_metadata()
    metadata.drop_all(bind=op.get_bind())
