"""
Tests for `_sql.py`'s model -> table mapping, rendered for each dialect without a database.

Compiling `CREATE TABLE` against a dialect object is enough to prove the dialect-specific parts
(identity columns, types, quoting) come out right for a database the suite may not have running.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING

import pytest
import sqlalchemy as sa
from pydantic import AwareDatetime, BaseModel
from sqlalchemy.dialects import postgresql, sqlite

from dltrack.serve._backend import _sql
from dltrack.serve._backend._foreign_keys import ForeignKey, ForeignKeyKind

if TYPE_CHECKING:
    from sqlalchemy.engine.interfaces import Dialect


class User(BaseModel, frozen=True, extra="forbid"):
    """Named like the real one on purpose: `user` is reserved in Postgres, so it must come out quoted."""

    id: int
    name: str
    score: float
    active: bool = True
    revision: int = 0
    tags: dict[str, str] = {}
    created: AwareDatetime | None = None


class _Child(BaseModel, frozen=True, extra="forbid"):
    id: int
    parent_id: int


def _ddl(dialect: Dialect, foreign_key: ForeignKey | None = None) -> str:
    metadata = sa.MetaData()
    parent = _sql.table_for(User, metadata, {})
    child = _sql.table_for(
        _Child, metadata, {User: parent}, {"parent_id": foreign_key} if foreign_key is not None else None
    )
    return " ".join(
        " ".join(str(sa.schema.CreateTable(t).compile(dialect=dialect)).split()) for t in (parent, child)
    )


@pytest.mark.parametrize(
    ("dialect", "expected"),
    [
        (
            sqlite.dialect(),
            [
                'CREATE TABLE "User" ( id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,',
                "score DOUBLE NOT NULL",
                "active BOOLEAN DEFAULT 1 NOT NULL",
                "revision INTEGER DEFAULT 0 NOT NULL",
                "tags JSON NOT NULL",
                "created TEXT )",
            ],
        ),
        (
            postgresql.dialect(),
            [
                'CREATE TABLE "User" ( id BIGINT GENERATED BY DEFAULT AS IDENTITY,',
                "score DOUBLE PRECISION NOT NULL",
                "active BOOLEAN DEFAULT true NOT NULL",
                "revision BIGINT DEFAULT 0 NOT NULL",
                "tags JSONB NOT NULL",
                "created TIMESTAMP WITH TIME ZONE,",
                "PRIMARY KEY (id)",
            ],
        ),
    ],
    ids=["sqlite", "postgres"],
)
def test_table_for_renders_each_dialects_types(dialect: Dialect, expected: list[str]) -> None:
    ddl = _ddl(dialect)
    for fragment in expected:
        assert fragment in ddl


@pytest.mark.parametrize(
    ("kind", "expected"),
    [
        (ForeignKeyKind.ATTRIBUTION, 'FOREIGN KEY(parent_id) REFERENCES "User" (id) )'),
        (ForeignKeyKind.OWNERSHIP, 'FOREIGN KEY(parent_id) REFERENCES "User" (id) ON DELETE CASCADE'),
    ],
)
def test_table_for_cascades_only_ownership_foreign_keys(kind: ForeignKeyKind, expected: str) -> None:
    assert expected in _ddl(postgresql.dialect(), ForeignKey(User, kind))


@pytest.mark.parametrize(
    ("foreign_keys", "unique_columns"),
    [({"nope": ForeignKey(User)}, None), (None, ["nope"])],
)
def test_table_for_rejects_unknown_columns(
    foreign_keys: dict[str, ForeignKey] | None, unique_columns: list[str] | None
) -> None:
    with pytest.raises(AssertionError, match="not present in model"):
        _sql.table_for(
            _Child, sa.MetaData(), {User: sa.Table("User", sa.MetaData())}, foreign_keys, unique_columns
        )


def test_column_type_unsupported_annotation_raises() -> None:
    with pytest.raises(NotImplementedError):
        _sql.column_type(complex)


@pytest.mark.parametrize(
    ("dialect", "bound"),
    [
        (sqlite.dialect(), "2026-01-01T00:00:00+00:00"),
        (postgresql.dialect(), datetime(2026, 1, 1, tzinfo=UTC)),
    ],
    ids=["sqlite", "postgres"],
)
@pytest.mark.parametrize("value", [datetime(2026, 1, 1, tzinfo=UTC), "2026-01-01T00:00:00Z"])
def test_utc_datetime_binds_text_on_sqlite_and_a_datetime_elsewhere(
    dialect: Dialect, bound: object, value: datetime | str
) -> None:
    assert _sql.UTCDateTime().process_bind_param(value, dialect) == bound


@pytest.mark.parametrize(
    "stored",
    [
        "2026-01-01T00:00:00Z",
        "2026-01-01T00:00:00+00:00",
        datetime(2026, 1, 1),
    ],  # a naive value is taken to be UTC
)
def test_utc_datetime_reads_back_aware(stored: datetime | str) -> None:
    assert _sql.UTCDateTime().process_result_value(stored, sqlite.dialect()) == datetime(
        2026, 1, 1, tzinfo=UTC
    )


def test_insert_leaves_an_unset_id_to_the_database() -> None:
    table = _sql.table_for(_Child, sa.MetaData(), {})
    assert "id" not in _sql.insert(table, _Child.model_construct(id=None, parent_id=1)).compile().params


def test_update_never_writes_revision() -> None:
    table = _sql.table_for(User, sa.MetaData(), {})
    params = _sql.update(table, User(id=1, name="a", score=1.0, revision=7)).compile().params
    assert "revision" not in params
    assert params["name"] == "a"


def test_construct_builds_model_from_row_by_column_name() -> None:
    row = {"created": None, "tags": {"env": "prod"}, "id": 1, "name": "run-1", "score": 0.5, "active": True}
    assert _sql.construct(User, row) == User(id=1, name="run-1", score=0.5, tags={"env": "prod"})
